# https://github.com/Homebrew/homebrew-bundle

cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'mpv-player/mpv'

brew 'chromedriver'
brew 'djview4'
brew 'elixir'
brew 'erlang'
brew 'git'
brew 'htop'
brew 'imagemagick'
brew 'macvim'
brew 'mc'
brew 'memcached'
brew 'mpv'
brew 'openssl'
brew 'phantomjs'
brew 'qt'
brew 'rbenv'
brew 'rbenv-ctags'
brew 'redis'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tree'
brew 'unrar'
brew 'wget'
brew 'zsh'

brew 'homebrew/versions/postgresql94', restart_service: true

cask 'chefdk'
cask 'flux'
cask 'gimp'
cask 'google-chrome'
cask 'ichm'
cask 'iterm2-beta'
cask 'karabiner'
cask 'skype'
cask 'smcfancontrol'
cask 'torbrowser'
cask 'utorrent'
cask 'vagrant'
cask 'virtualbox'
