#!/usr/bin/env ruby

require 'fileutils'
require 'open-uri'

git_bundles = %w[
  tpope/vim-fugitive
  scrooloose/nerdtree
  tpope/vim-unimpaired
  vim-ruby/vim-ruby
  tpope/vim-rails
  scrooloose/nerdcommenter
  tpope/vim-surround
  cakebaker/scss-syntax.vim
  jeetsukumaran/vim-buffergator
  tpope/vim-haml
  slim-template/vim-slim
  ap/vim-css-color
  kchmck/vim-coffee-script
  briancollins/vim-jst
  sstephenson/eco
  wincent/command-t
  vim-scripts/grep.vim
  vim-scripts/vimgrep.vim
  tpope/vim-endwise
  Keithbsmiley/rspec.vim
  saks/Specky
  scrooloose/syntastic
  flazz/vim-colorschemes
  bkad/CamelCaseMotion
  bling/vim-airline
  chriskempson/base16-vim
  ervandew/supertab
  aklt/plantuml-syntax
  kien/ctrlp
  xolox/vim-misc
  xolox/vim-session
  vim-scripts/LustyExplorer
]

# majutsushi/tagbar
# msanders/snipmate.vim
# Yggdroot/indentLine
# dtjm/plantuml-syntax

git_keep = []

bundles_dir = File.join(File.dirname(__FILE__), 'bundle')

FileUtils.mkdir bundles_dir unless File.exist? bundles_dir
FileUtils.cd bundles_dir

puts "trashing everything..."

Dir['*'].each {|d| FileUtils.rm_rf d unless git_keep.include?(d) }

puts "fetching plugins..."

git_bundles.each do |plugin|
  url = "git://github.com/#{plugin}"
  dir = url.split('/').last

  puts "  Unpacking #{url} into #{dir}"
  %x{git clone #{url} #{dir}}
  FileUtils.rm_rf File.join(dir, ".git")
end

puts "compiling command-t..."

# https://langui.sh/2014/03/10/wunused-command-line-argument-hard-error-in-future-is-a-harsh-mistress
environment = 'ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future"'
command_t_path = File.join 'command-t', 'ruby', 'command-t'
rvm_init_script = 'source $HOME/.rvm/scripts/rvm'
command_t_build_script = 'rvm use system && ruby extconf.rb && make'

puts %x{zsh -c 'cd #{command_t_path} && #{rvm_init_script} && #{environment} #{command_t_build_script}'}
