"*******************************************************************************
"                                                                              *
" version 7.4 and higher support ~/.vim/vimrc location                         *
"                                                                              *
" these keys generate the same characters:                                     *
"                                                                              *
" - <Tab> and <C-i>                                                            *
" - <CR> and <C-m>                                                             *
" - <Esc> and <C-[>                                                            *
" - <C-S-h> and <C-h> (any character)                                          *
"                                                                              *
"*******************************************************************************

"===============================================================================
"                                                                              =
" general options                                                              =
"                                                                              =
"===============================================================================

syntax on

set noautochdir
set nocompatible
set nospell
set nowrap

"-------------------------------------------------------------------------------
" backup and swap files
"-------------------------------------------------------------------------------

set backup
set noswapfile

" swap files (currently disabled)
" http://vim.wikia.com/wiki/Editing_crontab
"set directory=~/.vim/tmp//
"set backupskip+=/private/tmp/*

"-------------------------------------------------------------------------------
" buffers
"-------------------------------------------------------------------------------

" http://usevim.com/2012/10/19/vim101-set-hidden
set hidden
" http://vim.wikia.com/wiki/Using_tab_pages
" `newtab` causes all quickfix files (Ag, etc.) to be opened in new tab
set switchbuf=usetab

"-------------------------------------------------------------------------------
" completion
"-------------------------------------------------------------------------------

" menu,preview - default
set completeopt+=longest

set wildmenu
set wildmode=longest:full,full
" used by command-t and ctrlp - it should be kept in sync with ~/.agignore
"
" don't prefix directories relative to project root with asterisk -
" that is prefer public/* to */public/*.
" this is known to have caused problems with spec/vcr_cassettes/ directory:
" when refreshing it in nerdtree directory kept on collapsing all the time
set wildignore+=*.log,public/*,spec/vcr_cassettes/*,tmp/*,deps/*,node_modules/*

"-------------------------------------------------------------------------------
" diff
"-------------------------------------------------------------------------------

" show filler lines, use vertical split by default
set diffopt=filler,vertical

"-------------------------------------------------------------------------------
" editing
"-------------------------------------------------------------------------------

set colorcolumn=81
"execute 'set colorcolumn=' . join(range(81,250), ',')
set cpoptions+=$

"-------------------------------------------------------------------------------
" folding
" http://vimcasts.org/episodes/how-to-fold/
"-------------------------------------------------------------------------------

set foldenable
set foldlevelstart=10
" syntax folding might not work in some cases (e.g. in spec files)
set foldmethod=indent
set foldnestmax=10

"-------------------------------------------------------------------------------
" formatting
"-------------------------------------------------------------------------------

" NOTE: these options might be overriden by filetype plugins!
"
" t - auto-wrap text using textwidth
" c - auto-wrap comments using textwidth
" r - insert comment leader after <CR> in insert mode
" o - insert comment leader after 'o' or 'O' in normal mode
" q - allow formatting of comments with 'gq'
" l - don't break long lines in insert mode
" j - remove comment leader when joining lines
set formatoptions-=tc
set formatoptions+=rj

"-------------------------------------------------------------------------------
" indentation
"-------------------------------------------------------------------------------

" dumb auto indentation - copy indentation from previous line
" it's automatically enabled with plugin-specific indentation on
"set autoindent

set expandtab
set shiftround
set shiftwidth=2
set softtabstop=2
set tabstop=2

"-------------------------------------------------------------------------------
" navigation
"-------------------------------------------------------------------------------

set scrolloff=5

"-------------------------------------------------------------------------------
" search
"-------------------------------------------------------------------------------

set hlsearch
set incsearch

set ignorecase
set smartcase

"-------------------------------------------------------------------------------
" splitting
"-------------------------------------------------------------------------------

set splitbelow
set splitright

"-------------------------------------------------------------------------------
" visualize invisible characters
"-------------------------------------------------------------------------------

set list
set listchars=nbsp:·,tab:▸·,trail:·,precedes:«,extends:»

"===============================================================================
"                                                                              =
" performance tweaks                                                           =
"                                                                              =
" http://stackoverflow.com/questions/16902317                                  =
"                                                                              =
"===============================================================================

set lazyredraw
set regexpengine=2
set synmaxcol=200

"=============================================================================="
"                                                                              "
" look and feel                                                                "
"                                                                              "
"=============================================================================="

" disable beeping
set vb t_vb=

"-------------------------------------------------------------------------------
" colors
"-------------------------------------------------------------------------------

set transparency=0

"let g:solarized_bold = 1
"let g:solarized_contrast = 'normal'
"let g:solarized_diffmode = 'normal'
"let g:solarized_italic = 0
"let g:solarized_underline = 1

"colorscheme PaperColor
"colorscheme github
"colorscheme hybrid-light
"colorscheme ir_black_morr
"colorscheme ir_black_tap
"colorscheme scheakur
"colorscheme sebocean_dasha
"colorscheme solarized
"colorscheme summerfruit_tap
"colorscheme vylight

if hostname() == 'MacBook-Pro-Personal.local'
  set background=light
  colorscheme PaperColor
else
  set background=light
  colorscheme PaperColor
endif

"-------------------------------------------------------------------------------
" font
"-------------------------------------------------------------------------------

"set linespace=6
"set guifont=Andale\ Mono:h14
"set linespace=2
"set guifont=Andale\ Mono\ MT\ Std:h14
"set linespace=4
"set guifont=Cousine:h14
"set linespace=7
"set guifont=Droid\ Sans\ Mono\ for\ Powerline:h14
"set linespace=5
"set guifont=Fira\ Mono:h14
"set linespace=0
"set guifont=Inconsolata-dz\ For\ Powerline:h14
"set linespace=0
"set guifont=Inconsolata\ LGC\ For\ Powerline:h14
"set linespace=2
"set guifont=Input\ Mono\ Narrow:h13
"set linespace=6
"set guifont=MonacoB\ for\ Powerline:h13

if hostname() == 'MacBook-Pro-Personal.local'
  set linespace=5
  set guifont=Andale\ Mono\ MT\ Std:h14
else
  set linespace=5
  set guifont=Andale\ Mono\ MT\ Std:h14
endif

"-------------------------------------------------------------------------------
" gui options
"-------------------------------------------------------------------------------

" NOTE: flags 'rL' must be added in exactly this order (IDK why)!
"
" c - use console dialogs instead of gui ones
" r - right scrollbar is always present
" L - left scrollbar is present when there's a vertically split window
set guioptions+=c
set guioptions-=rL

" configure cursor blinking
" http://stackoverflow.com/a/39816241/3632318
"set guicursor+=a:blinkon600-blinkoff400
set guicursor+=a:blinkon0

"-------------------------------------------------------------------------------
" indicators
"-------------------------------------------------------------------------------

" highlight current line (might slow down navigation)
" this is the main cause of sluggish scrolling!
" set after colorscheme - or else it can be redefined inside it
set nocursorline
" hide mode indicator
set noshowmode
" show number of lines or characters selected in bottom right corner
set showcmd
" always show tabbar
set showtabline=2

" show line numbering
if hostname() == 'MacBook-Pro-Personal.local'
  set nonumber
else
  set number
endif

"-------------------------------------------------------------------------------
" startup
"-------------------------------------------------------------------------------

set shortmess+=I

" https://rvm.io/integration/vim
" https://github.com/scrooloose/syntastic/issues/1407
set shell=/bin/zsh
" http://stackoverflow.com/a/4642855/3632318
" (see last comment - using interactive shell can create problems)
"set shellcmdflag=-ic

" maximize on startup
" NOTE: setting columns to 999 maximizes the 1st column when using vimdiff!
"set lines=999
"set columns=999

"===============================================================================
"                                                                              =
" abbreviations                                                                =
"                                                                              =
"===============================================================================

iabbrev ii i18n_i
iabbrev lasnt last
iabbrev teh the
iabbrev tt i18n_t

"===============================================================================
"                                                                              =
" source external vim files                                                    =
"                                                                              =
"===============================================================================

runtime macros/matchit.vim

source ~/.vim/mappings.vim
source ~/.vim/autocommands.vim
source ~/.vim/plugins.vim
