# https://eslint.org/docs/rules/
env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:flowtype/recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - flowtype
# [<is_recommended>], default: <default_options>
#
# rule format:
#
# `name: enabled` or `name: [enabled, options]` where
# - `enabled` is one of `off` (0), `warn` (1) or `error` (2)
# - `options` are rule-specific configuration options
#
# if rule has no options, both forms are allowed:
# `name: enabled` and `name: [enabled]`
rules:
  # [ ], default: "never"
  comma-dangle:
    - warn
    - only-multiline
  # [ ], default: 4
  indent:
    - error
    - 2
  # [ ], default: "before": true, "after": true
  keyword-spacing:
    - error
    - after: true
      before: true
  # [ ], default: "unix"
  linebreak-style:
    - error
    - unix
  # [ ], default: ["error", 80]
  #max-len:
  #  - warn
  #  - 80
  # [ ], default: {"skipBlankLines": false, "ignoreComments": false}
  no-trailing-spaces:
    - error
  # [x], default: none
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  # [ ], default: "double"
  quotes:
    - error
    - single
  # [ ], default: "never"
  object-curly-spacing:
    - error
    - never
  # [ ], default: "always"
  semi:
    - error
    - always
  # [ ], default: "always"
  space-before-function-paren:
    - error
    - always
  react/jsx-handler-names:
    - warn
    - eventHandlerPrefix: _handle
  react/jsx-max-props-per-line:
    - warn
    - when: multiline
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-boolean-value:
    - error
    - never
  react/no-string-refs: error
  react/jsx-wrap-multilines:
    - error
    - declaration: parens-new-line
      assignment: parens-new-line
      return: parens-new-line
      arrow: parens-new-line
      condition: parens-new-line
      logical: ignore
      prop: ignore
  react/self-closing-comp:
    - error
    - component: true
      html: true
  react/jsx-closing-bracket-location:
    - error
  react/require-default-props:
    - error
    - forbidDefaultForRequired: true
  react/no-unused-prop-types:
    - error
